# Default configuration for Grok-3+ model
# DOI: 10.5281/zenodo.15341810

# Model architecture
model:
  vocab_size: 32000
  hidden_size: 2048
  num_layers: 24
  num_heads: 16
  intermediate_size: 8192
  max_position_embeddings: 4096
  layer_norm_eps: 1.0e-5
  use_fp8: true
  use_moe: true
  moe_layers: [2, 5, 8, 11, 14, 17, 20, 23]  # Layers that use MoE (0-indexed)
  num_experts: 8
  num_experts_per_tok: 2
  tie_word_embeddings: false
  gradient_checkpointing: true
  pad_token_id: 0
  eos_token_id: 1
  bos_token_id: 2

# Tokenizer settings
tokenizer:
  type: sentencepiece
  vocab_file: null  # Set at runtime
  max_length: 4096

# Training configuration
training:
  # Optimizer settings
  optimizer:
    type: adamw
    lr: 3.0e-4
    min_lr: 3.0e-5
    beta1: 0.9
    beta2: 0.95
    weight_decay: 0.1
    eps: 1.0e-8
    
  # Learning rate schedule
  lr_scheduler:
    type: cosine
    warmup_steps: 2000
    warmup_ratio: 0.01
    
  # Training parameters
  batch_size: 64
  grad_accum_steps: 4
  max_steps: 300000
  save_steps: 5000
  eval_steps: 1000
  logging_steps: 100
  
  # Mixed precision settings
  fp16: true
  bf16: false  # Use bfloat16 if available, otherwise use fp16
  
  # Distributed training
  distributed:
    enabled: true
    backend: nccl
    zero_stage: 3  # ZeRO stage for optimizer state partitioning
    
  # Auxiliary loss weight for MoE
  moe_aux_loss_weight: 0.01
  
  # Gradient clipping
  max_grad_norm: 1.0
  
  # Random seed
  seed: 42

# Data configuration
data:
  train_file: null  # Set at runtime
  validation_file: null  # Set at runtime
  text_column: "text"
  preprocessing:
    max_length: 4096
    
# Evaluation configuration
evaluation:
  # Benchmarks to evaluate on
  benchmarks:
    - mmlu:
        subset: "all"
    - gsm8k: {}
    - xnli:
        languages: ["en", "hi", "es"]
  
  # Metrics to compute
  metrics:
    - accuracy
    - perplexity
    
  # Generation parameters
  generation:
    max_length: 512
    temperature: 0.7
    top_p: 0.9
    do_sample: true
    num_beams: 1
    
# Logging configuration
logging:
  level: info
  use_wandb: true
  wandb:
    project: "grok3p"
    entity: null  # Set at runtime
    
# Paths configuration
paths:
  output_dir: "./outputs"
  cache_dir: "./cache"
  results_dir: "./results"
  
# System configuration
system:
  seed: 42
